version: '3'

services:
  mediawiki:
    image: deweiliu/mediawiki:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    container_name: mediawiki-container
    ports:
      - 8080:80