AWSTemplateFormatVersion: 2010-09-09
Resources:
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      BackupPolicy:
        Status: ENABLED
      FileSystemTags:
        - Key: Name
          Value: mediawiki
Outputs:
  FileSystemID:
    Value: !Ref FileSystem
    Export:
      Name: Mediawiki-EfsId
  FileSystemArn:
    Value: !GetAtt FileSystem.Arn
    Export:
      Name: Mediawiki-EfsArn